batch_size: 16
delta_exp: lps_gt
device: !!python/object/apply:torch.device
- cuda
- 6
early_stopping: 0
exp_name: gt2
gpu: 6
lr: 0.0001
lr_decay: 0.4
n_delta: 4
n_iters: null
n_transform: 16
num_epochs: 40
p_original: 0.5
patience: 30
pde: kdv
print_interval: 70
resample: diric
sample: 0
scheduler: step
seed: 2
sigma:
- 0.1
- 0.1
- 0.1
- 0.1
split: 4
test_batch_size: 1024
test_mode: false
time_future: 20
time_history: 20
train_samples: 10
transform_batch_size: 32
