batch_size: 4
device: !!python/object/apply:torch.device
- cuda
- 3
epochs: 100
exp_name: '2'
gpu: 3
lr: 0.0001
n_delta: 8
n_intervals: 4
patch_size: 8
pde: heat
seed: 2
sigma: 0.4
tau: 3.0
test_mode: false
th: 0.0001
weight_lipschitz: 1.0
weight_ortho: 3.0
weight_pde: 1.0
weight_sobolev: 1.0
