batch_size: 4
device: !!python/object/apply:torch.device
- cuda
- 4
epochs: 100
exp_name: '0'
gpu: 4
lr: 0.0001
n_delta: 4
n_intervals: 4
patch_size: 8
pde: kdv
seed: 0
sigma: 0.4
tau: 3.0
test_mode: false
th: 0.0001
weight_lipschitz: 1.0
weight_ortho: 3.0
weight_pde: 1.0
weight_sobolev: 1.0
